[project]
name = "unit-convertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.64.0",
    "ruff>=0.9.7",
    "streamlit>=1.42.2",
    "google-generativeai>=0.8.4",
]
